version: 2.1
jobs:
  one: # job #1
    docker:
      - image: circleci/ruby:2.4.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
    
  two: #job #2
    docker:
      - image: circleci/ruby:2.4.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "A more familar hello"
      - attach_workspace:
          at: my_workspace # this is needed since we need the output from the first job
          
      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then 
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
workflows:
  version: 2
  doubleWorkflow:
    jobs:
      - one
      - two:
          requires:
            - one
